#!/bin/sh
#
# Radically simple personal bootstrapping tool for macOS.
# https://github.com/nidi-sh/nidi.sh
set -o errexit -o nounset

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if ! command -v brew >/dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

[ -d "/opt/homebrew" ] && HOMEBREW_PREFIX="/opt/homebrew" || HOMEBREW_PREFIX="/usr/local"
eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"

export PATH="/usr/local/bin:$PATH"
if ! command -v nidi >/dev/null; then
    echo "Installing Usanidi..."
    brew install usanidi/tap/nidi
fi

nidi setup "$@" --directory "$SCRIPT_DIR/.."
